---
version: "3"
services:
  vpn:
    image: sevenrats/wireguard-client:next
    container_name: vpn
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config/vpn/data:/data/vpn
      - ./config/vpn/connection:/connection
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      service:
        ipv4_address: 172.20.0.20
    restart: unless-stopped

networks:
  service:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
